include:
    - project: 'renovate-bot/renovate-runner'
      file: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  RENOVATE_EXTRA_FLAGS: --autodiscover=true --onboarding=true --autodiscover-filter=thielepaul/renovate-gonum
  RENOVATE_LOG_FILE_LEVEL: "debug"
  CI_RENOVATE_IMAGE: renovate/renovate:34.66.1
renovate:
  rules:
    - when: always